### ISSUE TITLE
Document how to set up autocomplete

### ISSUE THREAD

**Issue by danvk** [flowtype/vim-flow#19]
```
/** @flow */
var x = ‘abc';
x.<C-x><C-o>
```

vim says “Omni completion (^O^N^P) Pattern not found”

I've installed vim-flow in `~/.vim/bundle/vim-flow` and am installing it using Pathogen.

**Comment by gabelevi** [comment]
Does

```JavaScript
/** @flow */
var x = { y: 123 };
x.<C-x><C-o>
```

work for you?

**Comment by danvk** [comment]
On one machine I get no matches. On another, I get seemingly every symbol under the sun:
![screen shot 2015-11-11 at 3 59 20 pm](https://cloud.githubusercontent.com/assets/98301/11102901/36952e04-888d-11e5-9a36-2d067b40c7e2.png)

**Comment by gabelevi** [comment]
So Flow has 2 types of autocomplete.

1. Member autocomplete. This is for when you do `myObj.<C-x><C-o>`
2. Identifier autocomplete. This is for when you do `myIden<C-x><C-o>`

For (1), we weren't handling the case where `myObj` is a string, number or boolean. I have an incoming diff to fix that. That diff should fix your example of

```
var x = ‘abc';
x.<C-x><C-o>
```

For (2), Flow just returns everything in scope. It's up to the IDE to filter them down, but vim-flow wasn't doing that. So #20 fixed it.

**Comment by gabelevi** [comment]
And thanks for the bug report! It was just the kick in the rear I needed to clean up a little bit of vim-flow!

**Comment by danvk** [comment]
I pulled down the latest version of `vim-flow`, but I'm still not seeing any completions.

For example, I would have expected this to complete `minOutlierSize`:
<img width="628" alt="screen shot 2015-11-11 at 5 34 58 pm" src="https://cloud.githubusercontent.com/assets/98301/11105069/91296346-889a-11e5-8f9c-ab0e48212c18.png">

Flow does understand the type of `insertStats`:
<img width="648" alt="screen shot 2015-11-11 at 5 34 42 pm" src="https://cloud.githubusercontent.com/assets/98301/11105072/95a41272-889a-11e5-972d-34672875e31c.png">

I tried explicitly running 

```
:so ~/.vim/bundle/vim-flow/autoload/flowcomplete.vim
```

as well, but it made no difference, so I do think that file is getting loaded.

**Comment by gabelevi** [comment]
Are you using flow v0.18.1? I think your case should work in v0.19.0 which I'm working on getting ready to deploy. If you have https://github.com/facebook/flow checked out to ~/flow, you can try running with with that version by doing this in vim

```vim
:let g:flow#flowpath = "~/flow/bin/flow"
```

Our autocomplete service is still under development, so there are a bunch of situations where it gives up too easily. If you're just trying to check if the plugin works, try something like

```JavaScript
var obj = {
  num: 123,
  str: 'hello',
};

obj.
```

**Comment by danvk** [comment]
I'm using 0.18.1, yeah.

I'm seeing really inconsistent behavior. For example, autocomplete works here:

![screen shot 2015-11-11 at 6 59 46 pm](https://cloud.githubusercontent.com/assets/98301/11106877/a328cb0c-88a6-11e5-9417-b88201d97dd8.png)

But in a seemingly similar context, I get completions which aren't specific:

![screen shot 2015-11-11 at 6 58 44 pm](https://cloud.githubusercontent.com/assets/98301/11106885/b3f4ebfa-88a6-11e5-98da-c02e83dc173b.png)

When I run `:FlowType` on `xs` and `basePairs`, they both come back as `Array<string>`.

The example you gave also doesn't yield specific completions:
![screen shot 2015-11-11 at 7 00 54 pm](https://cloud.githubusercontent.com/assets/98301/11106891/c2ada72c-88a6-11e5-9d72-28a3ca52ed94.png)

**Comment by danvk** [comment]
Looking forward to Flow 0.19! I'm excited about the coverage command.

**Comment by gabelevi** [comment]
I don't think the completions that are missing types are coming from Flow. Maybe those are coming from another plugin?

**Comment by danvk** [comment]
That's certainly possible. I'm not sure how this omnifunc stuff works.

In any case, in the `obj.` example, the flow completions don't come up at all. If I do `obj.nu<C-x><C-o>`, it suggests things like `getMinutes(` and `setMinutes(`, not `num`.

**Comment by laszbalo** [comment]
Same issue here. Using Flow 0.21.

**Comment by tomauty** [comment]
Experiencing this issue on 0.22.1. Not sure if I have conflicts with another autocomplete plugin or something.

**Comment by tomauty** [comment]
Nevermind, it does work.
