### ISSUE TITLE
Lots of characters when using neovim

### ISSUE THREAD

**Issue by wmonk** [flowtype/vim-flow#32]
Hi!

`vim-flow` is working nicely for me, got autocomplete working too 😄 

I'm having an issue though where the Quickfix window is including all the stuff listed below:
```
flowType: ^[]4;0;rgb:00/2b/36^[\^[]4;1;rgb:dc/32/2f^[\^[]4;2;rgb:85/99/00^[\^[]4;3;rgb:b5/89/00^[\^[]4;
4;rgb:26/8b/d2^[\^[]4;5;rgb:6c/71/c4^[\^[]4;6;rgb:2a/a1/98^[\^[]4;7;rgb:93/a1/a1^[\^[]4;8;rgb:65/7b/83^
[\^[]4;9;rgb:dc/32/2f^[\^[]4;10;rgb:85/99/00^[\^[]4;11;rgb:b5/89/00^[\^[]4;12;rgb:26/8b/d2^[\^[]4;13;rg
b:6c/71/c4^[\^[]4;14;rgb:2a/a1/98^[\^[]4;15;rgb:fd/f6/e3^[\^[]4;16;rgb:cb/4b/16^[\^[]4;17;rgb:d3/36/82^
[\^[]4;18;rgb:07/36/42^[\^[]4;19;rgb:58/6e/75^[\^[]4;20;rgb:83/94/96^[\^[]4;21;rgb:ee/e8/d5^[\^[]Pg93a1
a1^[\^[]Ph002b36^[\^[]Pi93a1a1^[\^[]Pj586e75^[\^[]Pk93a1a1^[\^[]Pl93a1a1^[\^[]Pm002b36^[\(unknown)
```
This is a screenshot too:
<img width="837" alt="screen shot 2016-07-29 at 09 54 24" src="https://cloud.githubusercontent.com/assets/175278/17243044/7a8c5ca6-5572-11e6-8ba1-adfae203e4a3.png">

I'm assuming this is a neovim issue as i've not seen it reported elsewhere, do you know of a fix?

Thanks!

**Comment by iamdustan** [comment]
what version of neovim and flow are you using?

**Comment by wmonk** [comment]
Hi!

```
nvim: 0.1.4
flow: 0.29
vim-flow: commit 10f7461c541ccdd9bf7ab59aace952f8c8b63cd7
```

**Comment by wmonk** [comment]
Welp, just updated vim-flow... all working fine now!
