### ISSUE TITLE
Syntax highlighting?

### ISSUE THREAD

**Issue by ahstro** [flowtype/vim-flow#45]
I would love it if the type annotations adopted the current colorscheme's comment color. Currently, it feels quite cluttered, and it's sometimes hard to see what is Flow and what is not.

I'm thinking this isn't _really_ the right repo for this, but couldn't find a better one and I haven't had time to give it a shot myself, but I'm hoping someone here will see it and either implement it here or separately.

Some good starting points might be reading [Writing Vim Syntax Plugins](https://robots.thoughtbot.com/writing-vim-syntax-plugins) and [Creating your own syntax files](http://vim.wikia.com/wiki/Creating_your_own_syntax_files), and looking at repos like [vim-jsx](https://github.com/mxw/vim-jsx), [vim-javascript](https://github.com/pangloss/vim-javascript), and [vim-es6](https://github.com/isRuslan/vim-es6) since they seem to do a similar thing as would be desired here, i.e., extending the base JavaScript syntax.

**Comment by monder** [comment]
@achao I'm not sure if its needed since the [vim-javascript](https://github.com/pangloss/vim-javascript) you linked already has full support for it.

See https://github.com/pangloss/vim-javascript#configuration-variables
```
let g:javascript_plugin_flow = 1
```

**Comment by ahstro** [comment]
Would you look at that! Thank you :)

**Comment by bounceme** [comment]
the issues are piling up as only one person contributes to flow support at vim-javascript. arguably, vim-javascript has no business providing full flow support. one recent example: https://github.com/pangloss/vim-javascript/issues/983#issuecomment-310467859

**Comment by amadeus** [comment]
I use flow at my work, but I don't actually have a very deep knowledge of it. I could definitely use help from someone who has a deep understanding of its intricacies, because I think it could help clean up a lot of the small bugs it has, if only I knew the flow specific rules for things.

**Comment by fabriziobertoglio1987** [comment]
![Screenshot from 2020-04-24 11-08-23](https://user-images.githubusercontent.com/24992535/80195321-f1f7a880-861b-11ea-92f5-269da5c779e4.png)

**Comment by fabOnReact** [comment]
not a vim expert ... so I don't think I can help here but it's painful not having syntax highlighting and folding on flow ... but I am  doing opensource full time ... currently trying to contribute to react-native

I can not multitask too much
Becoming very improducting, I wasted 2 hours this morning to figure this out
