### ISSUE TITLE
Commands don't exist, g:flow#omnifunc pattern not found?

### ISSUE THREAD

**Issue by scwood** [flowtype/vim-flow#47]
I have the plugin installed but none of the commands exist i.e. `FlowMake`. I can echo out the value of some variables: 

```
:echo g:flow#enable
1
```

But not others:

```
:echo g:flow#omnifunc
E121: Undefined variable: g:flow#omnifunc
E15: Invalid expression: g:flow#omnifunc
````

Minimal vimrc:

```
call plug#begin()

Plug 'flowtype/vim-flow'

call plug#end()
```

Any ideas?

**Comment by scwood** [comment]
Looks like `flow-bin` needs to be install globally. That fixed it.

**Comment by ingocraft** [comment]
#24  fixes
