### ISSUE TITLE
Empty Quickfix buffer

### ISSUE THREAD

**Issue by twopoint718** [flowtype/vim-flow#6]
I have the vim plugin installed and I have flow working (that is, running `flow` on the command line works). But I still get an empty Quickfix list when I save a `.js` file.

My vim is:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 22 2014 12:15:44)
MacOS X (unix) version
Included patches: 1-306
```

Flow version is:

```
Flow, a static type checker for Javascript, version 0.1.0
```

Any ideas about this. I feel like I have something misconfigured, but I can't figure out what.

**Comment by seanhess** [comment]
I had this same error. I installed flow via brew, as recommended on this page: http://flowtype.org/docs/getting-started.html#_

I've logged an issue for them to update on the flow repo https://github.com/facebook/flow/issues/305, but maybe it would be helpful to display an error message if the flow version is below an incompatible number or something. 

It's working now that I manually copied the 0.4.0 binary into my path.
