### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by wwwdata** [flowtype/vim-flow#64]
I am monitoring this project for quite a while now because I am actively using it. There are currently almost 10 open PRs. Is somebody taking care of this repo? Are you too busy and need help?

**Comment by gabelevi** [comment]
Help would be greatly appreciated. Honestly, I don't know much about vimscript & plugins and have been faking my way for years.

**Comment by gabelevi** [comment]
Just made a pass on the PRs - hope that helps :)
